### ISSUE TITLE
Almost there

### ISSUE THREAD

**Issue by BuilderGaming** [iKlem/GoulpLoader#5]
So you did a VERY good job updating and its very well. I am surely keeping this on my server but there is 1 glitch that you see on every other loading screen. The downloaded/downloading files count never changes or updates. Could you fix this or is this just a common java script error that every screen has.

**Comment by iKlem** [comment]
Have you a public Gmod server ? Because it never happened for me.

**Comment by BuilderGaming** [comment]
Its public. IP 74.91.116.162:27015

**Comment by BuilderGaming** [comment]
Ok. I did some working and I seem to fixed it. I was changing something and I somehow broke this.
